name: alumni_connect
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.15.2
  cloud_firestore: ^4.13.5
  firebase_analytics: ^10.7.4
  file_picker: ^6.1.1
  firebase_core: ^2.24.2
  intl: ^0.19.0
  flutter_rating_bar: ^4.0.1
  font_awesome_flutter: ^10.6.0
  flutter_staggered_grid_view: ^0.7.0
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  uuid: ^4.2.1
  webview_flutter: ^4.4.2
  image_picker: ^1.0.4
  firebase_storage: ^11.5.5



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/white-bluelogo.png"


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
   
